### PR TITLE
Fix (neuraforecast/core/cross-validation): Raise Exception when val_size+test_size is greater than min size of series.

### PR DESCRIPTION
**Pull request by marcopeix**
Right, if val_size+test_size is greater than the min size of a series, we show a warning, but the code still tries to run. In my test using the ETTm1 dataset, the following didn't fail immediately, but ran indefinitely: 

```python
nf.cross_validation(Y_df, val_size=2000000, test_size=2000000, n_windows=None)
```

I think it should raise an exception instead and stop running. I think this should solve #400

### CODE REVIEW

**Comment by jmoralez** [comment]
I think the underlying issue is that a bunch of windows filled with zeros are used for training, so this would be fixed by #1059.

**Comment by marcopeix** [comment]
> I think the underlying issue is that a bunch of windows filled with zeros are used for training, so this would be fixed by #1059.

Would it also solve #400 ?

**Comment by jmoralez** [comment]
I don't know what that means by "breaks". Do you get an error if you specify those numbers to be just slightly above the minimum length?

**Comment by marcopeix** [comment]
> I don't know what that means by "breaks". Do you get an error if you specify those numbers to be just slightly above the minimum length?

I get other errors, like `Exception: Time series is too short for training, consider setting a smaller input size or set start_padding_enabled=True`. You're right, the issue is not clear. I will ask for clarification and close this PR as it seems to introduce more problems than solutions.

**Pull request closed without merging**
