### PR TITLE
[FIX] Conformal prediction issues

### PR DESCRIPTION
**Pull request by elephaint**
- Addresses @jose-moralez comments
- Adds conformal prediction to docs in `mint.json`

### CODE REVIEW

**Comment by jmoralez** [comment]
Can you rerun the tutorial? The intervals should be different now

**Comment by elephaint** [comment]
> Can you rerun the tutorial? The intervals should be different now

Thanks, you're right, in my haste I had reran it but didn't see any changes but it is slightly different.

**Comment by jmoralez** [comment]
Thanks. I can't comment on that line but this has to be changed on the other method as well (line 542)

**Comment by elephaint** [comment]
> Thanks. I can't comment on that line but this has to be changed on the other method as well (line 542)

For f*cks sake I'm an idiot, jeez

**Review by jmoralez — APPROVED** [review]

**Pull request merged**
