### PR TITLE
Fixed: Exception: max_epochs is deprecated, use max_steps instead.

### PR DESCRIPTION
**Pull request by joseph-ruskiewicz**
Title says it all.  Appreciate all the work!

### CODE REVIEW

**Comment by jmoralez** [comment]
Thanks for this. Can you please also modify the README?

**Comment by jmoralez** [comment]
Ah yeah, my bad.

**Comment by jmoralez** [comment]
Hey @twobitunicorn, can you please sign the CLA?

**Comment by twobitunicorn** [comment]
@jmoralez my bad! all signed.

**Comment by jmoralez** [comment]
I think each commit has a different email. Can you maybe squash them into a single one with the same user?

**Comment by twobitunicorn** [comment]
That was weird.  Sorry about that.  Should be fixed.

**Review by jmoralez — APPROVED** [review]
Thanks!

**Pull request merged**
