### PR TITLE
TFT-Interpretability

### PR DESCRIPTION
**Pull request by amirouyanis**
Added **Interpretability for Temporal Fusion Transformer.**

Changed the TFT class to return the needed parameters for interpretability and implemented methods for interpretability plots.

### CODE REVIEW

**Comment by marcopeix** [comment]
Thanks for the contribution! Here are a few comments to improve your PR and get it merged:

- Merge the `main` branch into your working branch to update it
- There a lot of changes made to documentation notebooks that shouldn't be modified. Please, revert those changes so they match what is on the `main` branch.
- Ideally, we don't introduce new dependencies. Can you make it such that there's a method or attribute to extract the parameters, but then it's up to the user to download any plotting library to interpret them and plot them.

Let me know if you have any questions!

**Comment by amirouyanis** [comment]
> Thanks for the contribution! Here are a few comments to improve your PR and get it merged:
> 
> * Merge the `main` branch into your working branch to update it
> * There a lot of changes made to documentation notebooks that shouldn't be modified. Please, revert those changes so they match what is on the `main` branch.
> * Ideally, we don't introduce new dependencies. Can you make it such that there's a method or attribute to extract the parameters, but then it's up to the user to download any plotting library to interpret them and plot them.
> 
> Let me know if you have any questions!

Thank for you response and comments. 

All the changes you ask for are made. 
Let me know if other changes are needed.

**Review by marcopeix — APPROVED** [review]

**Comment by marcopeix** [comment]
@amirouyanis Thanks again for the PR, great work! Can you just add this header `| eval: false` to all the cells where you actually run the model? So all the cells after "Usage Example". That will make the tests pass. Thank you!

**Comment by amirouyanis** [comment]
> @amirouyanis Thanks again for the PR, great work! Can you just add this header `| eval: false` to all the cells where you actually run the model? So all the cells after "Usage Example". That will make the tests pass. Thank you!

@marcopeix Done! :)

**Review by marcopeix — APPROVED** [review]

**Pull request merged**
