### PR TITLE
On Windows, prevent long trial directory names

### PR DESCRIPTION
**Pull request by tg2k**
On Windows, prevent long trial directory names (https://github.com/ray-project/ray/issues/29586, https://github.com/Nixtla/neuralforecast/issues/526).

### CODE REVIEW

**Comment by tg2k** [comment]
Thanks @jmoralez, I hadn't realized. I pushed another change that may help.

**Comment by jmoralez** [comment]
Hey @tg2k. Are you able to provide a reproducible example of this? I've been trying to do that in #814 but it passes haha. If you can provide one I can include it there and merge this to make sure it fixes the issue. Then we can merge this to main.

**Comment by tg2k** [comment]
@jmoralez It's been about 3 months since I made a stab at a Windows environment, so my memory in this is a little fuzzy, and I don't have a reproducible example.

I believe my Windows-side directory path was 21 characters long. As an example of a Windows path that could be created, from https://github.com/Nixtla/neuralforecast/issues/526#issuecomment-1515829035 you can see a path like 

`C:\pathto\ray_results\train_tune_2023-04-20_15-07-40\train_tune_7f3f4_00000_0_check_val_every_n_epoch=100,hidden_size=512,hist_exog_list=spx_log_ret,input_size=20,learning_rate=0.0012_2023-04-20_15-07-43\lightning_logs\version_0\events.out.tfevents.1681974471.Desktop-DC.30528.0`

which is about 279 characters long. Windows maxes out at [260 characters](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry) unless you enable extended-length paths (as shown on that page), but for the most part support for those long paths is weak in Windows.

You can see from the example above that the default behavior encodes a lot of parameters into the path. If you have a long enough base path, or enough parameters (such as exogenous variables), you'll push the path over the limit (unless Ray-Tune has changed how it creates paths on Windows in the meantime).

**Comment by elephaint** [comment]
Trying to reproduce on Windows 11, no luck yet. 

A potential issue with this fix is that `trial_dirname_creator` is an [alpha feature](https://docs.ray.io/en/latest/tune/api/doc/ray.tune.TuneConfig.html)

**Review by jmoralez — APPROVED** [review]

**Pull request merged**
