### PR TITLE
feat: Added cross-validation tutorial

### PR DESCRIPTION
**Pull request by MMenchero**
This is part of the new docs for neuralforecast.

### CODE REVIEW

**Comment by MMenchero** [comment]
<p>All suggested changes have been implemented. </p>

---

 <a href='https://app.reviewnb.com/Nixtla/neuralforecast/pull/897/discussion/#comment-1959739884'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by MMenchero** [comment]
<p>thanks, missed that one</p>

---

 <a href='https://app.reviewnb.com/Nixtla/neuralforecast/pull/897/discussion/#comment-1969429462'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by MMenchero** [comment]
<p>TIL, that's pretty useful</p>

---

 <a href='https://app.reviewnb.com/Nixtla/neuralforecast/pull/897/discussion/#comment-1969429500'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by MMenchero** [comment]
<p>got it. </p>

---

 <a href='https://app.reviewnb.com/Nixtla/neuralforecast/pull/897/discussion/#comment-1971382588'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by MMenchero** [comment]
<p>I also missed it, but is now deleted. </p>

---

 <a href='https://app.reviewnb.com/Nixtla/neuralforecast/pull/897/discussion/#comment-1971382615'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by MMenchero** [comment]
<p>sure, I added a callout box and kept it simple in the main text. </p>

---

 <a href='https://app.reviewnb.com/Nixtla/neuralforecast/pull/897/discussion/#comment-1971854099'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by MMenchero** [comment]
<p>I'm now using the default values, but in order to keep Capi's suggestion of setting <code>step_size=horizon</code>, I had to remove the LSTM model since recurrent models don't support <code>step_size&gt;1</code>. Instead, I'm now using the MLP and the NBEATS models. </p>

---

 <a href='https://app.reviewnb.com/Nixtla/neuralforecast/pull/897/discussion/#comment-1971854132'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by MMenchero** [comment]
<p>I added an additional paragraph + plots at the end to further clarify the concept. It's at the end because I need to rename a column to make the plots and that is done in section 5.  </p>

---

 <a href='https://app.reviewnb.com/Nixtla/neuralforecast/pull/897/discussion/#comment-1971854173'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by cchallu — APPROVED** [review]

**Pull request merged**
